# Generated by Django 3.2.6 on 2021-08-19 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeclone_app', '0002_rename_comments_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='userRelpy',
            field=models.CharField(default=4, max_length=300),
            preserve_default=False,
        ),
    ]
