# Generated by Django 3.2.6 on 2021-08-21 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('youtubeclone_app', '0003_comment_userrelpy'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='userComment',
            new_name='body',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='like',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='userRelpy',
        ),
        migrations.AddField(
            model_name='comment',
            name='likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='comment',
            name='video_id',
            field=models.CharField(default=4, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=300)),
                ('comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='youtubeclone_app.comment')),
            ],
        ),
    ]
